# Generated by Django 3.1.3 on 2020-11-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifimanager', '0002_auto_20201111_0956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
