# Generated by Django 3.1.3 on 2020-11-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifimanager', '0004_auto_20201111_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chat_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='ID пользователя'),
        ),
    ]
