# Generated by Django 3.1.3 on 2020-11-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifimanager', '0005_auto_20201112_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Логин клиента')),
                ('active', models.BooleanField(choices=[(True, 'Активен'), (False, 'Не активен')], default=False, verbose_name='Активность')),
            ],
        ),
    ]
