# Generated by Django 3.1.3 on 2020-12-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifimanager', '0007_balancenotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directaccount',
            name='active',
            field=models.BooleanField(choices=[(True, 'Активен'), (False, 'Не активен')], default=True, verbose_name='Активность'),
        ),
        migrations.CreateModel(
            name='YandexYestStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spend', models.FloatField(verbose_name='Открут за вчерашний день')),
                ('balance', models.FloatField(verbose_name='Остаток бюджета')),
                ('days', models.PositiveIntegerField(verbose_name='Дней до израсходованиия бюджета')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifimanager.directaccount')),
            ],
        ),
    ]
