# Generated by Django 3.1.3 on 2020-12-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifimanager', '0008_auto_20201208_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='yandexyeststat',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата'),
        ),
    ]
