# Generated by Django 3.1.3 on 2021-02-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifimanager', '0009_yandexyeststat_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='Not specified', max_length=70, verbose_name='E-mail пользователя'),
        ),
    ]
